apiVersion: v1
kind: Service
metadata:
  labels:
    app: f1-ml-api
  name: f1-ml-api-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: f1-ml-api
  type: LoadBalancer
